CREATE TABLE IF NOT EXISTS users (
	id SERIAL PRIMARY KEY,
	email TEXT UNIQUE NOT NULL,
	password_hash TEXT NOT NULL,
	created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS robots (
	id SERIAL PRIMARY KEY,
	name TEXT NOT NULL,
	status TEXT NOT NULL CHECK (status IN ('idle', 'moving')),
	lat DOUBLE PRECISION NOT NULL,
	lon DOUBLE PRECISION NOT NULL,
	updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
